// This file is generated by Slice Machine. Update with care!

import Carousel from './Carousel';
import Events from './Events';
import Form from './Form';
import Introduction from './Introduction';
import Link from './Link';
import Press from './Press';
import Sponsors from './Sponsors';
import Table from './Table';
import Text from './Text';

export {
	Carousel,
	Events,
	Form,
	Introduction,
	Link,
	Press,
	Sponsors,
	Table,
	Text,
};

export const components = {
	carousel: Carousel,
	events: Events,
	form: Form,
	introduction: Introduction,
	link: Link,
	press: Press,
	sponsors: Sponsors,
	table: Table,
	text: Text,
};
