// This file is generated by Slice Machine. Update with care!

import Events from './Events';
import Form from './Form';
import FormField from './FormField';
import Introduction from './Introduction';
import Link from './Link';
import Press from './Press';
import Sponsors from './Sponsors';
import Table from './Table';
import Text from './Text';

export {
	Events,
	Form,
	FormField,
	Introduction,
	Link,
	Press,
	Sponsors,
	Table,
	Text,
};

export const components = {
	events: Events,
	form: Form,
	form_field: FormField,
	introduction: Introduction,
	link: Link,
	press: Press,
	sponsors: Sponsors,
	table: Table,
	text: Text,
};
